### ISSUE TITLE
[feature request] Show transaction cost

### ISSUE THREAD

**Issue by grandafrato** [hlongvu/elixium_wallet_cli#1]
It would be cool if the wallet would tell you how much of the money will be subtracted and given to the miners.

Example:
```
Enter Command: send <insert address here> <insert number here>
OK address: true
Fee would be <insert miner fee here>. Do you still want to continue?
(y/n): yes
Sent
```

**Comment by hlongvu** [comment]
yeah, I will include that in the next version. Currently the fee is default to 1.0 and can be change in config file.

**Comment by hlongvu** [comment]
Ask for fee at https://github.com/hlongvu/elixium_wallet_cli/commit/fa5f1743d0c916d939f2d8d654cec6f8f272aaaf
